# Generated by Django 3.2.7 on 2021-09-08 15:41

from django.db import migrations, models
import items.validators


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='pictures/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.CharField(max_length=10, validators=[items.validators.validate_price]),
        ),
        migrations.DeleteModel(
            name='PictureItem',
        ),
    ]
